# Generated by Django 2.2.6 on 2019-10-21 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('due', models.DateField(default=datetime.datetime(2019, 10, 21, 14, 50, 13, 830124))),
            ],
        ),
    ]
