# Generated by Django 2.2.6 on 2019-10-21 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateField(default=datetime.datetime(2019, 10, 21, 14, 50, 57, 716885, tzinfo=utc)),
        ),
    ]
