# Generated by Django 2.2.6 on 2019-10-21 14:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20191021_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='due',
            field=models.DateField(default=datetime.datetime(2019, 10, 21, 14, 52, 10, 867093, tzinfo=utc)),
        ),
    ]
